# Configures the Semantic Pull Requests App

# Always validate the PR title, and ignore the commits
titleOnly: true
# # You can define a list of valid scopes
# scopes:
#   - scope1
#   - scope2
#   ...
