name: Generate documentation

# Run this workflow on all pushes to master and pull requests
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  # This job checks if the docs can be generated and produce changes
  # If they do, a PR will be created with the changes
  check-and-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    outputs:
      CHANGES: ${{ steps.changes.outputs.CHANGES }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install --prefer-offline --frozen-lockfile

    - name: Compile TypeScript code
      run: yarn run build

    - name: Generate documentation
      run: yarn run docs:generate

    # Trigger this step only when pushing to master
    - name: Create or update PR
      if: |
        github.event_name == 'push' && 
        github.ref == 'refs/heads/master'
      uses: ./.github/actions/generateTypedDocs
      with:
        githubToken: ${{ secrets.DOCS_UPDATE_TOKEN }}
      env:
        CI: true
