name: Generate documentation

# Run this job on all pushes to master and pull requests
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # We need npm@7 for the workspaces feature
    - name: Update npm to >=7
      run: "[ $(npm -v | cut -d. -f1) -lt 7 ] && npm i -g npm@7"

    - name: Install dependencies
      run: npm ci

    - name: Test documentation generation
      run: npm run docs:generate
