name: Update toLogEntry overview

# Only run this on changes to the master branch
on:
  push:
    branches:
      - master

jobs:
  generate-overview:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # We need npm@7 for the workspaces feature
    - name: Update npm to >=7
      run: "[ $(npm -v | cut -d. -f1) -lt 7 ] && npm i -g npm@7"

    - name: Install dependencies
      run: npm ci

    - name: Update overview
      uses: ./.github/actions/toLogEntry
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true
